//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PumpServiceServiceReference
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    //[Microsoft.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="StatisticService", Namespace="http://schemas.datacontract.org/2004/07/PumpService")]
    public partial class StatisticService : object
    {
        
        private int AllTactsField;
        
        private int ErrorTactsField;
        
        private int SuccessTactsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AllTacts
        {
            get
            {
                return this.AllTactsField;
            }
            set
            {
                this.AllTactsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ErrorTacts
        {
            get
            {
                return this.ErrorTactsField;
            }
            set
            {
                this.ErrorTactsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SuccessTacts
        {
            get
            {
                return this.SuccessTactsField;
            }
            set
            {
                this.SuccessTactsField = value;
            }
        }
    }
    
   // [Microsoft.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://Microsoft.ServiceModel.Samples", ConfigurationName="PumpServiceServiceReference.IPumpService", CallbackContract=typeof(PumpServiceServiceReference.IPumpServiceCallback))]
    public interface IPumpService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Microsoft.ServiceModel.Samples/IPumpService/RunScript", ReplyAction="http://Microsoft.ServiceModel.Samples/IPumpService/RunScriptResponse")]
        System.Threading.Tasks.Task RunScriptAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Microsoft.ServiceModel.Samples/IPumpService/UpdateAndCompileScript", ReplyAction="http://Microsoft.ServiceModel.Samples/IPumpService/UpdateAndCompileScriptResponse" +
            "")]
        System.Threading.Tasks.Task UpdateAndCompileScriptAsync(string fileName);
    }
    
    //[Microsoft.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public interface IPumpServiceCallback
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Microsoft.ServiceModel.Samples/IPumpService/UpdateStatistic", ReplyAction="http://Microsoft.ServiceModel.Samples/IPumpService/UpdateStatisticResponse")]
        void UpdateStatistic(PumpServiceServiceReference.StatisticService statistics);
    }
    
    //[Microsoft.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public interface IPumpServiceChannel : PumpServiceServiceReference.IPumpService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
   // [Microsoft.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil-lib", "2.0.3.0")]
    public partial class PumpServiceClient : System.ServiceModel.DuplexClientBase<PumpServiceServiceReference.IPumpService>, PumpServiceServiceReference.IPumpService
    {
        
        public PumpServiceClient(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance)
        {
        }
        
        public PumpServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName)
        {
        }
        
        public PumpServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress)
        {
        }
        
        public PumpServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress)
        {
        }
        
        public PumpServiceClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task RunScriptAsync()
        {
            return base.Channel.RunScriptAsync();
        }
        
        public System.Threading.Tasks.Task UpdateAndCompileScriptAsync(string fileName)
        {
            return base.Channel.UpdateAndCompileScriptAsync(fileName);
        }
    }
}
